# Generated by Django 3.2.15 on 2022-09-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
